import { User, Milestone, Task } from '../types/task';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-quynhnv',
    name: 'Nguyễn Văn Quỳnh',
    account: 'QuynhNV',
    role: 'Admin',
    specializations: ['PO'],
    cccd: '001099036785',
    bankAccount: '04891636001 - TPB - NGUYEN VAN QUYNH',
    email: 'nguyenvanquynh396lp@gmail.com',
    phone: '0388607463',
    technologies: 'PO, Angular, JavaSpring',
    birthDate: 1999,
    totalEffort: 0,
  },
  {
    id: 'usr-thanhndt',
    name: 'Nguyễn Đăng Tuấn Thanh',
    account: 'ThanhNDT',
    role: 'Leader',
    specializations: ['DevOps'],
    bankAccount: '03582265201 - TPB - NGUYEN DANG TUAN THANH',
    email: 'thanhtnt160299@gmail.com',
    phone: '0976263139',
    technologies: 'BA, Java-Spring, DevOps',
    birthDate: 1999,
    totalEffort: 0,
  },
  {
    id: 'usr-namnv',
    name: 'Hán Văn Nam',
    account: 'NamNV',
    role: 'Leader',
    specializations: ['AI'],
    cccd: '026099002753',
    bankAccount: '02651095701 - TPB - HAN VAN NAM',
    email: 'namadam2507@gmail.com',
    phone: '0868149135',
    technologies: 'AI, ReactJS, Angular',
    birthDate: 1999,
    totalEffort: 0,
  },
  {
    id: 'usr-lichdt',
    name: 'Đoàn Trọng Lịch',
    account: 'LichDT',
    role: 'Leader',
    specializations: ['Design'],
    cccd: '034099011985',
    bankAccount: '8117101999 - MB - DOAN TRONG LICH',
    email: 'tronglich.a2@gmail.com',
    phone: '0926066296',
    technologies: 'Designer',
    birthDate: 1999,
    totalEffort: 0,
  },
  {
    id: 'usr-huyfq',
    name: 'Phạm Quang Huy',
    account: 'HuyFQ',
    role: 'Leader',
    specializations: ['BA'],
    bankAccount: '04650639801 - TPB - PHAM QUANG HUY',
    email: 'phamhuy6999@gmail.com',
    phone: '0989427489',
    technologies: 'BA',
    birthDate: 1999,
    totalEffort: 0,
  },
  {
    id: 'usr-hailh',
    name: 'Lê Hồng Hải',
    account: 'HaiLH',
    role: 'Leader',
    specializations: ['FE'],
    bankAccount: '9972126518 - VCB - Le Hong Hai',
    email: 'lehonghai2307.hbc@gmail.com',
    technologies: 'ReactJS, Angular, NextJS',
    birthDate: 1999,
    totalEffort: 0,
  },
  {
    id: 'usr-viethq',
    name: 'Hoàng Quốc Việt',
    account: 'VietHQ',
    role: 'Leader',
    specializations: ['FE'],
    bankAccount: '19038283250011 - TCB - HOANG QUOC VIET',
    email: 'viethq.developer@gmail.com',
    phone: '0978595918',
    technologies: 'Angular, ReactJs, VueJs, ReactNative',
    birthDate: 1999,
    totalEffort: 0,
  },
  {
    id: 'usr-longvt',
    name: 'Vũ Tầm Long',
    account: 'LongVT',
    role: 'Leader',
    specializations: ['BE'],
    bankAccount: '19070189584010 - TCB - Vu Tam Long',
    email: 'vutamlong251@gmail.com',
    phone: '0819122238',
    technologies: 'Java Spring, Angular, Flutter',
    birthDate: 2000,
    totalEffort: 0,
  },
  {
    id: 'usr-dungpm',
    name: 'Phạm Hải Đăng',
    account: 'DungPM',
    role: 'Leader',
    specializations: ['SA'],
    cccd: '038093025377',
    bankAccount: '8888888836 - TCB - PHAM HAI DANG',
    email: 'thangvu453@gmail.com',
    phone: '0829427558',
    technologies: 'Java Spring, SA',
    birthDate: 1993,
    totalEffort: 0,
  },
  {
    id: 'usr-hoannv',
    name: 'Nguyễn Việt Hoàn',
    account: 'HoanNV',
    role: 'Leader',
    specializations: ['BE'],
    cccd: '037201001937',
    bankAccount: '2207215941 - BIDV - Nguyen Viet Hoan',
    email: 'hoannv251@gmail.com',
    phone: '0985712135',
    technologies: 'Java Spring, DevOps',
    birthDate: 2001,
    totalEffort: 0,
  },
  {
    id: 'usr-vuongnt',
    name: 'Nguyễn Thành Vương',
    account: 'VuongNT',
    role: 'Member',
    specializations: ['BA'],
    cccd: '001095001674',
    bankAccount: '04105887601 - TPB - Nguyen Thanh Vuong',
    email: 'sahodmitry@gmail.com',
    phone: '0987964931',
    technologies: 'BA',
    birthDate: 1995,
    totalEffort: 0,
  },
  {
    id: 'usr-tinhdd',
    name: 'Đào Đức Tính',
    account: 'TinhDD',
    role: 'Member',
    specializations: ['FE'],
    cccd: '067201000017',
    bankAccount: '0342506775 - TPB - DAO DUC TINH',
    email: 'tinhdd.tnhdd@gmail.com',
    phone: '0342506775',
    technologies: 'Angular, DevOps',
    birthDate: 2001,
    totalEffort: 0,
  },
  {
    id: 'usr-dattq',
    name: 'Trần Quốc Đạt',
    account: 'DatTQ',
    role: 'Member',
    specializations: ['FE'],
    cccd: '019200000789',
    bankAccount: '0335267789 - MB - TRAN QUOC DAT',
    email: 'dattranquoc20@gmail.com',
    phone: '0868130164',
    technologies: 'Angular, React, NextJS',
    birthDate: 1998,
    totalEffort: 0,
  },
  {
    id: 'usr-binhtnt',
    name: 'Trần Hoàng Thái Bình',
    account: 'BinhTNT',
    role: 'Leader',
    specializations: ['QA'],
    cccd: '079200022145',
    bankAccount: '0358504024 - VIB - TRAN HOANG THAI BINH',
    email: 'thtb3110@gmail.com',
    phone: '0358504024',
    technologies: 'QA',
    birthDate: 1997,
    totalEffort: 0,
  },
  {
    id: 'usr-dungdv',
    name: 'Đoàn Việt Dũng',
    account: 'DungDV',
    role: 'Member',
    specializations: ['BE'],
    cccd: '001200024458',
    bankAccount: '025758443 - VIB - DOAN VIET DUNG',
    email: 'doanvietdung0103@gmail.com',
    phone: '0868603426',
    technologies: 'Java, Spring, DevOps',
    birthDate: 2000,
    totalEffort: 0,
  },
  {
    id: 'usr-sonmc',
    name: 'Mai Công Sơn',
    account: 'SonNC',
    role: 'Member',
    specializations: ['BA'],
    cccd: '025080000801',
    bankAccount: '026.0071.0701 - TPB - MAI CONG SON',
    email: 'sonmc80@gmail.com',
    phone: '0335622389',
    technologies: 'Java, Angular, React',
    birthDate: 1980,
    totalEffort: 0,
  },
  {
    id: 'usr-anhnmm',
    name: 'Nguyễn Hoàng Minh Anh',
    account: 'AnhNMM',
    role: 'Member',
    specializations: ['BA'],
    cccd: '003305002161',
    bankAccount: '0803036692 - VietinBank - NGUYEN HOANG MINH ANH',
    email: 'minhanhsa2007@gmail.com',
    phone: '0803036692',
    technologies: 'BA',
    birthDate: 2005,
    totalEffort: 0,
  },
  {
    id: 'usr-nhiht',
    name: 'Huỳnh Thúy Nhi',
    account: 'NhiHT',
    role: 'Member',
    specializations: ['BA'],
    cccd: '066199000011',
    bankAccount: '190432543 - VPBank - HUYNH THUY NHI',
    email: 'nellyjujy@gmail.com',
    phone: '0942220437',
    technologies: 'BA',
    birthDate: 1999,
    totalEffort: 0,
  },
  {
    id: 'usr-anhptm',
    name: 'Phạm Thị Minh Anh',
    account: 'AnhPTM',
    role: 'Member',
    specializations: ['BA'],
    cccd: '034304003648',
    bankAccount: '1903834676014 - TCB - PHAM THI MINH ANH',
    email: 'anhpm1104@gmail.com',
    phone: '0388624532',
    technologies: 'BA',
    birthDate: 2004,
    totalEffort: 0,
  },
  {
    id: 'usr-ductm',
    name: 'Trần Minh Đức',
    account: 'DucTM',
    role: 'Member',
    specializations: ['FE'],
    cccd: '042201008184',
    bankAccount: '0201000730524 - VCB - TRAN MINH DUC',
    email: 'ducatm50k@gmail.com',
    phone: '0585161654',
    technologies: 'Java, Angular',
    birthDate: 2001,
    totalEffort: 0,
  },
  {
    id: 'usr-thont',
    name: 'Nguyễn Trường Thọ',
    account: 'ThoNT',
    role: 'Member',
    specializations: ['FE'],
    cccd: '077201004330',
    bankAccount: '1448648 - ACB - NGUYEN TRUONG THO',
    email: 'nguyentruongtho.dev@gmail.com',
    phone: '0395431919',
    technologies: 'Java/python, angular',
    birthDate: 2001,
    totalEffort: 0,
  },
  {
    id: 'usr-phulv',
    name: 'Lê Văn Phú',
    account: 'PhuLV',
    role: 'Member',
    specializations: ['BE'],
    cccd: '045203000365',
    bankAccount: '1015953194 - VCB - LE VAN PHU',
    email: 'lvphu.work@gmail.com',
    phone: '0814321006',
    technologies: 'Java Spring, angular',
    birthDate: 2003,
    totalEffort: 0,
  },
  {
    id: 'usr-truongnk',
    name: 'Nguyễn Nhật Trường',
    account: 'TruongNK',
    role: 'Member',
    specializations: ['FE'],
    cccd: '064205000307',
    bankAccount: '1030475573 - VCB - NGUYEN NHAT TRUONG',
    email: 'truongnhatt20072005@gmail.com',
    phone: '0385908714',
    technologies: 'python, angular',
    birthDate: 2005,
    totalEffort: 0,
  },
  {
    id: 'usr-giangnvm',
    name: 'Nguyễn Văn Minh Giang',
    account: 'GiangNVM',
    role: 'Member',
    specializations: ['FE'],
    cccd: '075205017046',
    bankAccount: '1040440108 - VCB - NGUYEN VAN MINH GIANG',
    email: 'minhgiang882@gmail.com',
    phone: '0868391750',
    technologies: 'python, angular',
    birthDate: 2005,
    totalEffort: 0,
  },
  {
    id: 'usr-loinv',
    name: 'Nguyễn Văn Lợi',
    account: 'LoiNV',
    role: 'Advisor',
    specializations: ['FE'],
    cccd: '079202010549',
    bankAccount: '079202010549 - MB - NGUYEN VAN LOI',
    email: 'nguyenvanloi1999@gmail.com',
    phone: '0383277878',
    technologies: 'Angular, DotNet',
    birthDate: 1999,
    totalEffort: 0,
  },
  {
    id: 'usr-khanhtp',
    name: 'Trần Phúc Khánh',
    account: 'KhanhTP',
    role: 'Advisor',
    specializations: ['Design'],
    cccd: '048205002172',
    bankAccount: '8987828452 - TCB - Tran Phuc Khanh',
    email: 'tranphuckhanh582@gmail.com',
    phone: '0897828452',
    technologies: 'Designer',
    birthDate: 2005,
    totalEffort: 0,
  },
];

export const INITIAL_MILESTONES: Milestone[] = [
  {
    id: 'ms-design-1',
    title: 'Milestone 1: Foundation',
    description: 'Quy trình quan trọng, tài liệu hướng dẫn và onboarding nhân sự mới',
    order: 1,
    status: 'In Progress',
    targetDate: '2026-09-30',
    role: 'Design',
  },
  {
    id: 'ms-design-2',
    title: 'Milestone 2:',
    description: '',
    order: 2,
    status: 'In Progress',
    targetDate: '2026-10-15',
    role: 'Design',
  },
];

export const INITIAL_TASKS: Task[] = [
  // Milestone 1 (9 tasks)
  {
    id: 'tsk-design-1-1',
    title: 'Dashboard Framework',
    priority: 'High',
    role: 'Design',
    estimatedEffort: 8,
    actualEffort: 0,
    status: 'To do',
    assigneeAccount: '',
    milestoneId: 'ms-design-1',
    orderInMilestone: 1,
    completionPercentage: 0,
    createdBy: 'LichDT',
    createdAt: '2026-09-17T01:00:00.000Z',
    weekNumber: 93,
    year: 2026,
    activityLogs: [
      {
        id: 'log-ms1-1',
        timestamp: '2026-09-17T01:00:00.000Z',
        authorName: 'Đoàn Trọng Lịch',
        authorAccount: 'LichDT',
        authorRole: 'Leader',
        actionType: 'CREATE',
        summary: 'Khởi tạo công việc mới',
      },
    ],
  },
  {
    id: 'tsk-design-1-2',
    title: 'Phân quyền & Quản lý người dùng',
    role: 'Design',
    estimatedEffort: 4,
    actualEffort: 0,
    status: 'To do',
    assigneeAccount: '',
    milestoneId: 'ms-design-1',
    orderInMilestone: 2,
    completionPercentage: 0,
    createdBy: 'LichDT',
    createdAt: '2026-09-17T01:00:00.000Z',
    weekNumber: 93,
    year: 2026,
    activityLogs: [
      {
        id: 'log-ms1-2',
        timestamp: '2026-09-17T01:00:00.000Z',
        authorName: 'Đoàn Trọng Lịch',
        authorAccount: 'LichDT',
        authorRole: 'Leader',
        actionType: 'CREATE',
        summary: 'Khởi tạo công việc mới',
      },
    ],
  },
  {
    id: 'tsk-design-1-3',
    title: 'Hệ thống Thông báo (Notification)',
    role: 'Design',
    estimatedEffort: 2,
    actualEffort: 0,
    status: 'To do',
    assigneeAccount: '',
    milestoneId: 'ms-design-1',
    orderInMilestone: 3,
    completionPercentage: 0,
    createdBy: 'LichDT',
    createdAt: '2026-09-17T01:00:00.000Z',
    weekNumber: 93,
    year: 2026,
    activityLogs: [
      {
        id: 'log-ms1-3',
        timestamp: '2026-09-17T01:00:00.000Z',
        authorName: 'Đoàn Trọng Lịch',
        authorAccount: 'LichDT',
        authorRole: 'Leader',
        actionType: 'CREATE',
        summary: 'Khởi tạo công việc mới',
      },
    ],
  },
  {
    id: 'tsk-design-1-4',
    title: 'Quản lý File đính kèm (File Attachment)',
    role: 'Design',
    estimatedEffort: 2,
    actualEffort: 0,
    status: 'To do',
    assigneeAccount: '',
    milestoneId: 'ms-design-1',
    orderInMilestone: 4,
    completionPercentage: 0,
    createdBy: 'LichDT',
    createdAt: '2026-09-17T01:00:00.000Z',
    weekNumber: 93,
    year: 2026,
    activityLogs: [
      {
        id: 'log-ms1-4',
        timestamp: '2026-09-17T01:00:00.000Z',
        authorName: 'Đoàn Trọng Lịch',
        authorAccount: 'LichDT',
        authorRole: 'Leader',
        actionType: 'CREATE',
        summary: 'Khởi tạo công việc mới',
      },
    ],
  },
  {
    id: 'tsk-design-1-5',
    title: 'Dịch vụ Email (Email Service)',
    role: 'Design',
    estimatedEffort: 2,
    actualEffort: 0,
    status: 'To do',
    assigneeAccount: '',
    milestoneId: 'ms-design-1',
    orderInMilestone: 5,
    completionPercentage: 0,
    createdBy: 'LichDT',
    createdAt: '2026-09-17T01:00:00.000Z',
    weekNumber: 93,
    year: 2026,
    activityLogs: [
      {
        id: 'log-ms1-5',
        timestamp: '2026-09-17T01:00:00.000Z',
        authorName: 'Đoàn Trọng Lịch',
        authorAccount: 'LichDT',
        authorRole: 'Leader',
        actionType: 'CREATE',
        summary: 'Khởi tạo công việc mới',
      },
    ],
  },
  {
    id: 'tsk-design-1-6',
    title: 'Nhật ký hệ thống (Audit Log cơ bản)',
    role: 'Design',
    estimatedEffort: 2,
    actualEffort: 0,
    status: 'To do',
    assigneeAccount: '',
    milestoneId: 'ms-design-1',
    orderInMilestone: 6,
    completionPercentage: 0,
    createdBy: 'LichDT',
    createdAt: '2026-09-17T01:00:00.000Z',
    weekNumber: 93,
    year: 2026,
    activityLogs: [
      {
        id: 'log-ms1-6',
        timestamp: '2026-09-17T01:00:00.000Z',
        authorName: 'Đoàn Trọng Lịch',
        authorAccount: 'LichDT',
        authorRole: 'Leader',
        actionType: 'CREATE',
        summary: 'Khởi tạo công việc mới',
      },
    ],
  },
  {
    id: 'tsk-design-1-7',
    title: 'Master Data Framework & Design System chuẩn',
    role: 'Design',
    estimatedEffort: 3,
    actualEffort: 0,
    status: 'To do',
    assigneeAccount: '',
    milestoneId: 'ms-design-1',
    orderInMilestone: 7,
    completionPercentage: 0,
    createdBy: 'LichDT',
    createdAt: '2026-09-17T01:00:00.000Z',
    weekNumber: 93,
    year: 2026,
    activityLogs: [
      {
        id: 'log-ms1-7',
        timestamp: '2026-09-17T01:00:00.000Z',
        authorName: 'Đoàn Trọng Lịch',
        authorAccount: 'LichDT',
        authorRole: 'Leader',
        actionType: 'CREATE',
        summary: 'Khởi tạo công việc mới',
      },
    ],
  },
  {
    id: 'tsk-design-1-8',
    title: 'Các thành phần dùng chung (Common Elements)',
    role: 'Design',
    estimatedEffort: 4,
    actualEffort: 0,
    status: 'To do',
    assigneeAccount: '',
    milestoneId: 'ms-design-1',
    orderInMilestone: 8,
    completionPercentage: 0,
    createdBy: 'LichDT',
    createdAt: '2026-09-17T01:00:00.000Z',
    weekNumber: 93,
    year: 2026,
    activityLogs: [
      {
        id: 'log-ms1-8',
        timestamp: '2026-09-17T01:00:00.000Z',
        authorName: 'Đoàn Trọng Lịch',
        authorAccount: 'LichDT',
        authorRole: 'Leader',
        actionType: 'CREATE',
        summary: 'Khởi tạo công việc mới',
      },
    ],
  },
  {
    id: 'tsk-design-1-9',
    title: 'Màn hình Đăng nhập (Login)',
    role: 'Design',
    estimatedEffort: 8,
    actualEffort: 4,
    status: 'In Progress',
    assigneeAccount: 'LichDT',
    milestoneId: 'ms-design-1',
    orderInMilestone: 9,
    completionPercentage: 50,
    createdBy: 'LichDT',
    createdAt: '2026-09-17T01:00:00.000Z',
    weekNumber: 93,
    year: 2026,
    activityLogs: [
      {
        id: 'log-ms1-9-1',
        timestamp: '2026-09-17T01:00:00.000Z',
        authorName: 'Đoàn Trọng Lịch',
        authorAccount: 'LichDT',
        authorRole: 'Leader',
        actionType: 'CREATE',
        summary: 'Khởi tạo công việc mới',
      },
      {
        id: 'log-ms1-9-2',
        timestamp: '2026-09-17T01:05:00.000Z',
        authorName: 'Đoàn Trọng Lịch',
        authorAccount: 'LichDT',
        authorRole: 'Leader',
        actionType: 'REPORT_SUBMIT',
        summary: 'Cập nhật tiến độ: In Progress (50%) - 4h',
      },
    ],
  },

  // Milestone 2 (7 tasks)
  {
    id: 'tsk-design-2-1',
    title: 'Organization Chart',
    role: 'Design',
    estimatedEffort: 3,
    actualEffort: 0,
    status: 'To do',
    assigneeAccount: '',
    milestoneId: 'ms-design-2',
    orderInMilestone: 1,
    completionPercentage: 0,
    createdBy: 'LichDT',
    createdAt: '2026-09-17T01:00:00.000Z',
    weekNumber: 93,
    year: 2026,
    activityLogs: [
      {
        id: 'log-ms2-1',
        timestamp: '2026-09-17T01:00:00.000Z',
        authorName: 'Đoàn Trọng Lịch',
        authorAccount: 'LichDT',
        authorRole: 'Leader',
        actionType: 'CREATE',
        summary: 'Khởi tạo công việc mới',
      },
    ],
  },
  {
    id: 'tsk-design-2-2',
    title: 'Working Schedule (Lịch làm việc)',
    role: 'Design',
    estimatedEffort: 8,
    actualEffort: 0,
    status: 'To do',
    assigneeAccount: '',
    milestoneId: 'ms-design-2',
    orderInMilestone: 2,
    completionPercentage: 0,
    createdBy: 'LichDT',
    createdAt: '2026-09-17T01:00:00.000Z',
    weekNumber: 93,
    year: 2026,
    activityLogs: [
      {
        id: 'log-ms2-2',
        timestamp: '2026-09-17T01:00:00.000Z',
        authorName: 'Đoàn Trọng Lịch',
        authorAccount: 'LichDT',
        authorRole: 'Leader',
        actionType: 'CREATE',
        summary: 'Khởi tạo công việc mới',
      },
    ],
  },
  {
    id: 'tsk-design-2-3',
    title: 'Phân hệ CRM (Quản lý Khách hàng & Tương tác)',
    role: 'Design',
    estimatedEffort: 2,
    actualEffort: 0,
    status: 'To do',
    assigneeAccount: '',
    milestoneId: 'ms-design-2',
    orderInMilestone: 3,
    completionPercentage: 0,
    createdBy: 'LichDT',
    createdAt: '2026-09-17T01:00:00.000Z',
    weekNumber: 93,
    year: 2026,
    activityLogs: [
      {
        id: 'log-ms2-3',
        timestamp: '2026-09-17T01:00:00.000Z',
        authorName: 'Đoàn Trọng Lịch',
        authorAccount: 'LichDT',
        authorRole: 'Leader',
        actionType: 'CREATE',
        summary: 'Khởi tạo công việc mới',
      },
    ],
  },
  {
    id: 'tsk-design-2-4',
    title: 'Contact and Interaction Management (Quản lý Liên hệ & Tương tác)',
    role: 'Design',
    estimatedEffort: 2,
    actualEffort: 0,
    status: 'To do',
    assigneeAccount: '',
    milestoneId: 'ms-design-2',
    orderInMilestone: 4,
    completionPercentage: 0,
    createdBy: 'LichDT',
    createdAt: '2026-09-17T01:00:00.000Z',
    weekNumber: 93,
    year: 2026,
    activityLogs: [
      {
        id: 'log-ms2-4',
        timestamp: '2026-09-17T01:00:00.000Z',
        authorName: 'Đoàn Trọng Lịch',
        authorAccount: 'LichDT',
        authorRole: 'Leader',
        actionType: 'CREATE',
        summary: 'Khởi tạo công việc mới',
      },
    ],
  },
  {
    id: 'tsk-design-2-5',
    title: 'Phân hệ SC (Chuỗi cung ứng & Danh mục)',
    role: 'Design',
    estimatedEffort: 2,
    actualEffort: 0,
    status: 'To do',
    assigneeAccount: '',
    milestoneId: 'ms-design-2',
    orderInMilestone: 5,
    completionPercentage: 0,
    createdBy: 'LichDT',
    createdAt: '2026-09-17T01:00:00.000Z',
    weekNumber: 93,
    year: 2026,
    activityLogs: [
      {
        id: 'log-ms2-5',
        timestamp: '2026-09-17T01:00:00.000Z',
        authorName: 'Đoàn Trọng Lịch',
        authorAccount: 'LichDT',
        authorRole: 'Leader',
        actionType: 'CREATE',
        summary: 'Khởi tạo công việc mới',
      },
    ],
  },
  {
    id: 'tsk-design-2-6',
    title: 'Category (Quản lý Danh mục)',
    role: 'Design',
    estimatedEffort: 2,
    actualEffort: 0,
    status: 'To do',
    assigneeAccount: '',
    milestoneId: 'ms-design-2',
    orderInMilestone: 6,
    completionPercentage: 0,
    createdBy: 'LichDT',
    createdAt: '2026-09-17T01:00:00.000Z',
    weekNumber: 93,
    year: 2026,
    activityLogs: [
      {
        id: 'log-ms2-6',
        timestamp: '2026-09-17T01:00:00.000Z',
        authorName: 'Đoàn Trọng Lịch',
        authorAccount: 'LichDT',
        authorRole: 'Leader',
        actionType: 'CREATE',
        summary: 'Khởi tạo công việc mới',
      },
    ],
  },
  {
    id: 'tsk-design-2-7',
    title: 'Employee Profile',
    role: 'Design',
    estimatedEffort: 2,
    actualEffort: 0,
    status: 'To do',
    assigneeAccount: '',
    milestoneId: 'ms-design-2',
    orderInMilestone: 7,
    completionPercentage: 0,
    createdBy: 'LichDT',
    createdAt: '2026-09-17T01:00:00.000Z',
    weekNumber: 93,
    year: 2026,
    activityLogs: [
      {
        id: 'log-ms2-7',
        timestamp: '2026-09-17T01:00:00.000Z',
        authorName: 'Đoàn Trọng Lịch',
        authorAccount: 'LichDT',
        authorRole: 'Leader',
        actionType: 'CREATE',
        summary: 'Khởi tạo công việc mới',
      },
    ],
  },
];

export const INITIAL_PROJECT_RESOURCES: any[] = [
  // --- Level 0: Business Plan ---
  {
    id: 'res-1',
    level: 'Business Plan',
    name: 'Sales, Strategy',
    content: 'Sale, Marketing, Strategy',
    tool: 'Google doc',
    primaryLink: 'https://docs.google.com/document/d/1sPkO5Ap2qF20aRLR_Az9qdRtWuahnpl3OnhbKqGIW8/edit',
    primaryLinkLabel: 'Saho | GMM | Strategy - Sales',
    order: 1,
  },
  {
    id: 'res-2',
    level: 'Business Plan',
    name: 'Estimate',
    content: 'Ước tính nỗ lực & ngân sách phát triển',
    tool: 'Google doc',
    primaryLink: 'https://docs.google.com/document/d/1sPkO5Ap2qF20aRLR_Az9qdRtWuahnpl3OnhbKqGIW8/edit',
    primaryLinkLabel: 'Saho | GMM | Estimate',
    order: 2,
  },
  {
    id: 'res-3',
    level: 'Business Plan',
    name: 'Landing Page',
    content: 'Trang giới thiệu sản phẩm & Onboarding',
    tool: 'Web',
    primaryLink: 'https://docs.google.com/document/d/1sPkO5Ap2qF20aRLR_Az9qdRtWuahnpl3OnhbKqGIW8/edit',
    primaryLinkLabel: 'Saho | GMM | Landing Page',
    order: 3,
  },
  {
    id: 'res-4',
    level: 'Business Plan',
    name: 'Sample Product',
    content: 'Angular - Typescript Demo',
    tool: 'Google AI Studio',
    primaryLink: 'https://docs.google.com/document/d/1sPkO5Ap2qF20aRLR_Az9qdRtWuahnpl3OnhbKqGIW8/edit',
    primaryLinkLabel: 'Saho | GMM | Sample Product (Demo)',
    order: 4,
  },
  {
    id: 'res-5',
    level: 'Business Plan',
    name: 'Security Rule',
    content: 'Quy định bảo mật thông tin & phân quyền hệ thống',
    tool: 'Docs',
    primaryLink: 'https://docs.google.com/document/d/1sPkO5Ap2qF20aRLR_Az9qdRtWuahnpl3OnhbKqGIW8/edit',
    primaryLinkLabel: 'Saho | GMM | Security Rule',
    order: 5,
  },

  // --- Level 1: Business ---
  {
    id: 'res-6',
    level: 'Level 1 - Business',
    name: 'Development Rule',
    content: 'Quy định quy trình phát triển sản phẩm',
    tool: 'Docs',
    primaryLink: 'https://docs.google.com/document/d/1sPkO5Ap2qF20aRLR_Az9qdRtWuahnpl3OnhbKqGIW8/edit',
    primaryLinkLabel: 'Saho | GMM | Development Rule',
    order: 6,
  },
  {
    id: 'res-7',
    level: 'Level 1 - Business',
    name: 'Requirement',
    content: 'Screen Flow, Master Plan',
    tool: 'Draw.io',
    primaryLink: 'https://draw.io',
    primaryLinkLabel: 'Saho | GMM | Requirement',
    originLink: 'https://docs.google.com/document/d/1sPkO5Ap2qF20aRLR_Az9qdRtWuahnpl3OnhbKqGIW8/edit',
    originLinkLabel: 'Saho | GMM | Requirement (Bản tổng hợp)',
    order: 7,
  },
  {
    id: 'res-8',
    level: 'Level 1 - Business',
    name: 'Function Tree',
    content: 'Site map hệ thống',
    tool: 'Draw.io',
    primaryLink: 'https://draw.io',
    primaryLinkLabel: 'Saho | GMM | Site Map',
    originLink: 'https://docs.google.com/document/d/1sPkO5Ap2qF20aRLR_Az9qdRtWuahnpl3OnhbKqGIW8/edit',
    originLinkLabel: 'Saho | GMM | Sitemap (Bản tổng hợp)',
    order: 8,
  },
  {
    id: 'res-9',
    level: 'Level 1 - Business',
    name: 'Backlog',
    content: 'Danh sách backlog dự án',
    tool: 'Google Sheets',
    primaryLink: 'https://docs.google.com/spreadsheets/d/1sPkO5Ap2qF20aRLR_Az9qdRtWuahnpl3OnhbKqGIW8/edit',
    primaryLinkLabel: 'Saho | GMM | Backlog',
    order: 9,
  },
  {
    id: 'res-10',
    level: 'Level 1 - Business',
    name: 'SRS',
    content: 'Software Requirement Specification',
    tool: 'Google sheet',
    primaryLink: 'https://docs.google.com/spreadsheets/d/1sPkO5Ap2qF20aRLR_Az9qdRtWuahnpl3OnhbKqGIW8/edit',
    primaryLinkLabel: 'Saho | GMM | SRS',
    order: 10,
  },

  // --- Level 2: Design ---
  {
    id: 'res-11',
    level: 'Level 2 - Design',
    name: 'Usecase Diagram',
    content: 'Biểu đồ Usecase chi tiết',
    tool: 'Draw.io',
    primaryLink: 'https://draw.io',
    primaryLinkLabel: 'Saho | GMM | Usecase',
    originLink: 'https://docs.google.com/document/d/1sPkO5Ap2qF20aRLR_Az9qdRtWuahnpl3OnhbKqGIW8/edit',
    originLinkLabel: 'Saho | GMM | Usecase (Bản tổng hợp)',
    order: 11,
  },
  {
    id: 'res-12',
    level: 'Level 2 - Design',
    name: 'FE | Architecture',
    content: 'Kiến trúc ứng dụng Front-End',
    tool: 'Draw.io',
    primaryLink: 'https://draw.io',
    primaryLinkLabel: 'Saho | GMM | FE | Architecture',
    order: 12,
  },
  {
    id: 'res-13',
    level: 'Level 2 - Design',
    name: 'BE | Architecture',
    content: 'Kiến trúc hệ thống Back-End',
    tool: 'Draw.io',
    primaryLink: 'https://draw.io',
    primaryLinkLabel: 'Saho | GMM | BE | Architecture',
    order: 13,
  },
  {
    id: 'res-14',
    level: 'Level 2 - Design',
    name: 'Sequence Diagram',
    content: 'Biểu đồ trình tự Sequence',
    tool: 'Draw.io',
    primaryLink: 'https://draw.io',
    primaryLinkLabel: 'Saho | GMM | Sequence',
    originLink: 'https://docs.google.com/document/d/1sPkO5Ap2qF20aRLR_Az9qdRtWuahnpl3OnhbKqGIW8/edit',
    originLinkLabel: 'Saho | GMM | Sequence (Bản tổng hợp)',
    order: 14,
  },
  {
    id: 'res-15',
    level: 'Level 2 - Design',
    name: 'FE Solution',
    content: 'Giải pháp giao diện Front-End',
    tool: 'Draw.io',
    primaryLink: 'https://draw.io',
    primaryLinkLabel: 'Saho | GMM | FE Solution',
    originLink: 'https://docs.google.com/document/d/1sPkO5Ap2qF20aRLR_Az9qdRtWuahnpl3OnhbKqGIW8/edit',
    originLinkLabel: 'Saho | GMM | FE Solution (Bản tổng hợp)',
    order: 15,
  },
  {
    id: 'res-16',
    level: 'Level 2 - Design',
    name: 'BE Solution',
    content: 'Giải pháp xử lý máy chủ Back-End',
    tool: 'Draw.io',
    primaryLink: 'https://draw.io',
    primaryLinkLabel: 'Saho | GMM | BE Solution',
    originLink: 'https://docs.google.com/document/d/1sPkO5Ap2qF20aRLR_Az9qdRtWuahnpl3OnhbKqGIW8/edit',
    originLinkLabel: 'Saho | GMM | BE Solution (Bản tổng hợp)',
    order: 16,
  },
  {
    id: 'res-17',
    level: 'Level 2 - Design',
    name: 'Figma design',
    content: 'Thiết kế màn hình & UI Kit Figma',
    tool: 'Figma',
    primaryLink: 'https://figma.com',
    primaryLinkLabel: 'Saho | GMM | Desgin Figma',
    order: 17,
  },

  // --- Level 3: Implementation ---
  {
    id: 'res-18',
    level: 'Level 3 - Implementation',
    name: 'ERD (Entity Relationship Diagram)',
    content: 'Sơ đồ thực thể quan hệ cơ sở dữ liệu',
    tool: 'Draw.io',
    primaryLink: 'https://draw.io',
    primaryLinkLabel: 'Saho | GMM | ERD',
    originLink: 'https://docs.google.com/document/d/1sPkO5Ap2qF20aRLR_Az9qdRtWuahnpl3OnhbKqGIW8/edit',
    originLinkLabel: 'Saho | GMM | ERD (Bản tổng hợp)',
    order: 18,
  },
  {
    id: 'res-19',
    level: 'Level 3 - Implementation',
    name: 'Class diagram',
    content: 'Sơ đồ lớp đối tượng',
    tool: 'Draw.io',
    primaryLink: 'https://draw.io',
    primaryLinkLabel: 'Saho | GMM | Class Diagram',
    originLink: 'https://docs.google.com/document/d/1sPkO5Ap2qF20aRLR_Az9qdRtWuahnpl3OnhbKqGIW8/edit',
    originLinkLabel: 'Saho | GMM | Class Diagram (Bản tổng hợp)',
    order: 19,
  },
  {
    id: 'res-20',
    level: 'Level 3 - Implementation',
    name: 'Database Design',
    content: 'Thiết kế bảng & quan hệ CSDL',
    tool: 'Draw.io',
    primaryLink: 'https://draw.io',
    primaryLinkLabel: 'Saho | GMM | Database',
    originLink: 'https://docs.google.com/document/d/1sPkO5Ap2qF20aRLR_Az9qdRtWuahnpl3OnhbKqGIW8/edit',
    originLinkLabel: 'Saho | GMM | Database Design (Bản tổng hợp)',
    order: 20,
  },
  {
    id: 'res-21',
    level: 'Level 3 - Implementation',
    name: 'Database Materials',
    content: 'Tài liệu tham khảo cấu trúc dữ liệu',
    tool: 'Sheet',
    primaryLink: 'https://docs.google.com/spreadsheets/d/1sPkO5Ap2qF20aRLR_Az9qdRtWuahnpl3OnhbKqGIW8/edit',
    primaryLinkLabel: 'Saho | GMM | Database Material',
    originLink: 'https://docs.google.com/spreadsheets/d/1sPkO5Ap2qF20aRLR_Az9qdRtWuahnpl3OnhbKqGIW8/edit',
    originLinkLabel: 'Saho | GMM | Database Material (Bản tổng hợp)',
    order: 21,
  },
  {
    id: 'res-22',
    level: 'Level 3 - Implementation',
    name: 'TestCase',
    content: 'Kịch bản kiểm thử phần mềm',
    tool: 'Sheet',
    primaryLink: 'https://docs.google.com/spreadsheets/d/1sPkO5Ap2qF20aRLR_Az9qdRtWuahnpl3OnhbKqGIW8/edit',
    primaryLinkLabel: 'Saho | GMM | Testcase',
    order: 22,
  },
  {
    id: 'res-23',
    level: 'Level 3 - Implementation',
    name: 'Template',
    content: 'All modules *Tabs*',
    tool: 'Draw.io',
    primaryLink: 'https://draw.io',
    primaryLinkLabel: 'Saho | GMM | Template',
    originLink: 'https://docs.google.com/document/d/1sPkO5Ap2qF20aRLR_Az9qdRtWuahnpl3OnhbKqGIW8/edit',
    originLinkLabel: 'Saho | GMM | Template (Bản tổng hợp)',
    order: 23,
  },
  {
    id: 'res-24',
    level: 'Level 3 - Implementation',
    name: 'Technology',
    content: 'Design, FE, BE, DevOps, QA,...',
    tool: 'Sheet',
    primaryLink: 'https://docs.google.com/spreadsheets/d/1sPkO5Ap2qF20aRLR_Az9qdRtWuahnpl3OnhbKqGIW8/edit',
    primaryLinkLabel: 'Saho | GMM | Technology',
    order: 24,
  },
  {
    id: 'res-25',
    level: 'Level 3 - Implementation',
    name: 'AWS Cost',
    content: 'Dự toán & tối ưu chi phí hạ tầng mây',
    tool: 'Sheet',
    primaryLink: 'https://docs.google.com/spreadsheets/d/1sPkO5Ap2qF20aRLR_Az9qdRtWuahnpl3OnhbKqGIW8/edit',
    primaryLinkLabel: 'Saho | GMM | Aws Cost',
    order: 25,
  },
  {
    id: 'res-26',
    level: 'Level 3 - Implementation',
    name: 'Dynamic System',
    content: 'Sơ đồ luồng hệ thống động',
    tool: 'Draw.io',
    primaryLink: 'https://draw.io',
    primaryLinkLabel: 'Saho | GMM | Dynamic System',
    order: 26,
  },
  {
    id: 'res-27',
    level: 'Level 3 - Implementation',
    name: 'Test Task Management',
    content: 'Sheet quản lý công việc V2',
    tool: 'Sheet',
    primaryLink: 'https://docs.google.com/spreadsheets/d/1sPkO5Ap2qF20aRLR_Az9qdRtWuahnpl3OnhbKqGIW8/edit',
    primaryLinkLabel: 'Saho | GMM (V2)',
    order: 27,
  },
];

