import { User, Milestone, Task } from '../types/task';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-1',
    name: 'Quỳnh NV (Admin)',
    account: 'QuynhNV',
    role: 'Admin',
    specializations: ['BA', 'Design'],
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
  },
  {
    id: 'usr-2',
    name: 'Vương NT (Leader BA)',
    account: 'VuongNT',
    role: 'Leader',
    specializations: ['BA'],
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
  },
  {
    id: 'usr-3',
    name: 'Nhi HT',
    account: 'NhiHT',
    role: 'Member',
    specializations: ['BA'],
    avatarUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150',
  },
  {
    id: 'usr-4',
    name: 'Anh NHM',
    account: 'AnhNHM',
    role: 'Member',
    specializations: ['BA', 'FE'],
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
  },
  {
    id: 'usr-5',
    name: 'Anh PTM',
    account: 'AnhPTM',
    role: 'Member',
    specializations: ['BA'],
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150',
  },
  {
    id: 'usr-6',
    name: 'Lịch DT (Leader Design)',
    account: 'LichDT',
    role: 'Leader',
    specializations: ['Design', 'BA'],
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
  },
  {
    id: 'usr-7',
    name: 'Tính DD',
    account: 'TinhDD',
    role: 'Member',
    specializations: ['FE', 'BE'],
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150',
  },
  {
    id: 'usr-8',
    name: 'Đạt TQ',
    account: 'DatTQ',
    role: 'Member',
    specializations: ['FE', 'BE'],
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150',
  },
];

export const INITIAL_MILESTONES: Milestone[] = [
  {
    id: 'ms-1',
    title: 'Milestone 1: Setup & Onboarding Requirements',
    description: 'Quy trình quan trọng, tài liệu hướng dẫn và onboarding nhân sự mới',
    targetDate: '2026-09-15',
    order: 1,
    status: 'In Progress',
  },
  {
    id: 'ms-2',
    title: 'Milestone 2: Design Rule & HR1 Workflow Breakdown',
    description: 'Xây dựng quy tắc Design Estimation và chuẩn hóa luồng công việc HR1',
    targetDate: '2026-09-22',
    order: 2,
    status: 'In Progress',
  },
  {
    id: 'ms-3',
    title: 'Milestone 3: Front-End Core Components & Signals',
    description: 'Nghiên cứu giải pháp FE, chuyển đổi CVA control và các component hệ thống',
    targetDate: '2026-09-30',
    order: 3,
    status: 'Planned',
  },
];

export const INITIAL_TASKS: Task[] = [
  // BA Tasks
  {
    id: 'tsk-1250',
    title: 'BA | Viết tài liệu phần "Working schedule"',
    role: 'BA',
    estimatedEffort: 2,
    actualEffort: 2,
    status: 'To do',
    assigneeAccount: 'VuongNT',
    milestoneId: 'ms-1',
    orderInMilestone: 1,
    completionPercentage: 0,
    weekNumber: 37,
    year: 2026,
    lastSubmittedAt: '2026-09-10T14:00:00.000Z',
    isSubmittedLate: false,
  },
  {
    id: 'tsk-1252',
    title: 'BA | Check "IMPORTANT RULE & Development Process" with QuynhNV',
    role: 'BA',
    estimatedEffort: 1,
    actualEffort: 1,
    status: 'Done',
    assigneeAccount: 'NhiHT',
    milestoneId: 'ms-1',
    orderInMilestone: 2,
    completionPercentage: 100,
    weekNumber: 37,
    year: 2026,
    lastSubmittedAt: '2026-09-11T09:30:00.000Z',
    isSubmittedLate: false,
  },
  {
    id: 'tsk-1253',
    title: 'BA | Check "BA & BA Estimate" with HuyPQ',
    role: 'BA',
    estimatedEffort: 1,
    actualEffort: 1,
    status: 'Done',
    assigneeAccount: 'NhiHT',
    milestoneId: 'ms-1',
    orderInMilestone: 3,
    completionPercentage: 100,
    weekNumber: 37,
    year: 2026,
    lastSubmittedAt: '2026-09-11T09:30:00.000Z',
    isSubmittedLate: false,
  },
  {
    id: 'tsk-1254',
    title: 'BA | Guide newbie how to read documents | Phạm Thị Minh Anh',
    role: 'BA',
    estimatedEffort: 0.5,
    actualEffort: 0.5,
    status: 'Done',
    assigneeAccount: 'NhiHT',
    milestoneId: 'ms-1',
    orderInMilestone: 4,
    completionPercentage: 100,
    weekNumber: 37,
    year: 2026,
    lastSubmittedAt: '2026-09-11T09:30:00.000Z',
    isSubmittedLate: false,
  },
  {
    id: 'tsk-1255',
    title: 'BA | Study Product (sheet "Resources", "Requirement")',
    role: 'BA',
    estimatedEffort: 16,
    actualEffort: 18,
    status: 'In Progress',
    assigneeAccount: 'NhiHT',
    milestoneId: 'ms-1',
    orderInMilestone: 5,
    completionPercentage: 65,
    weekNumber: 37,
    year: 2026,
    lastSubmittedAt: '2026-09-11T10:15:00.000Z',
    isSubmittedLate: false,
  },
  {
    id: 'tsk-1257',
    title: 'BA | Check "IMPORTANT RULE & Development Process" with QuynhNV',
    role: 'BA',
    estimatedEffort: 0.5,
    actualEffort: 0.5,
    status: 'Done',
    assigneeAccount: 'AnhNHM',
    milestoneId: 'ms-1',
    orderInMilestone: 6,
    completionPercentage: 100,
    weekNumber: 37,
    year: 2026,
    lastSubmittedAt: '2026-09-11T22:45:00.000Z',
    isSubmittedLate: true,
  },
  {
    id: 'tsk-1258',
    title: 'BA | Check "BA & BA Estimate" with HuyPQ',
    role: 'BA',
    estimatedEffort: 1,
    actualEffort: 1,
    status: 'Done',
    assigneeAccount: 'AnhNHM',
    milestoneId: 'ms-1',
    orderInMilestone: 7,
    completionPercentage: 100,
    weekNumber: 37,
    year: 2026,
    lastSubmittedAt: '2026-09-11T22:45:00.000Z',
    isSubmittedLate: true,
  },
  {
    id: 'tsk-1259',
    title: 'BA | Study Product (sheet "Resources", "Requirement")',
    role: 'BA',
    estimatedEffort: 10,
    actualEffort: 10,
    status: 'In Progress',
    assigneeAccount: 'AnhNHM',
    milestoneId: 'ms-1',
    orderInMilestone: 8,
    completionPercentage: 50,
    weekNumber: 37,
    year: 2026,
    lastSubmittedAt: '2026-09-11T22:45:00.000Z',
    isSubmittedLate: true,
  },
  {
    id: 'tsk-1260',
    title: 'BA | Market Research Customer Information & Contact/Interaction Management',
    role: 'BA',
    estimatedEffort: 12,
    actualEffort: 12,
    status: 'Done',
    assigneeAccount: 'AnhNHM',
    milestoneId: 'ms-1',
    orderInMilestone: 9,
    completionPercentage: 100,
    weekNumber: 37,
    year: 2026,
    lastSubmittedAt: '2026-09-11T22:45:00.000Z',
    isSubmittedLate: true,
  },
  {
    id: 'tsk-1262',
    title: 'BA | Study rule "Important Rule", "Development Process", "Estimate Rule - BA"',
    role: 'BA',
    estimatedEffort: 3,
    actualEffort: 0,
    status: 'To do',
    assigneeAccount: 'AnhPTM',
    milestoneId: 'ms-1',
    orderInMilestone: 10,
    completionPercentage: 0,
    weekNumber: 37,
    year: 2026,
  },
  {
    id: 'tsk-1263',
    title: 'BA | Check "IMPORTANT RULE & Development Process" with QuynhNV',
    role: 'BA',
    estimatedEffort: 1,
    actualEffort: 0,
    status: 'To do',
    assigneeAccount: 'AnhPTM',
    milestoneId: 'ms-1',
    orderInMilestone: 11,
    completionPercentage: 0,
    weekNumber: 37,
    year: 2026,
  },

  // Design Tasks
  {
    id: 'tsk-1267',
    title: 'Design | Check "IMPORTANT RULE", "Development Process" with QuynhNV',
    role: 'Design',
    estimatedEffort: 1,
    actualEffort: 0,
    status: 'To do',
    assigneeAccount: 'LichDT',
    milestoneId: 'ms-2',
    orderInMilestone: 1,
    completionPercentage: 0,
    weekNumber: 37,
    year: 2026,
  },
  {
    id: 'tsk-1268',
    title: 'Define "Design Estimation" Rule',
    role: 'Design',
    estimatedEffort: 4,
    actualEffort: 2,
    status: 'To do',
    assigneeAccount: 'LichDT',
    milestoneId: 'ms-2',
    orderInMilestone: 2,
    completionPercentage: 40,
    weekNumber: 37,
    year: 2026,
  },
  {
    id: 'tsk-1269',
    title: 'Breakdown task from milestones 1-2',
    role: 'Design',
    estimatedEffort: 3,
    actualEffort: 3,
    status: 'In Progress',
    assigneeAccount: 'LichDT',
    milestoneId: 'ms-2',
    orderInMilestone: 3,
    completionPercentage: 70,
    weekNumber: 37,
    year: 2026,
    lastSubmittedAt: '2026-09-11T12:00:00.000Z',
    isSubmittedLate: false,
  },
  {
    id: 'tsk-1270',
    title: 'Finalize the HR1 workflow',
    role: 'Design',
    estimatedEffort: 4,
    actualEffort: 4,
    status: 'In Progress',
    assigneeAccount: 'LichDT',
    milestoneId: 'ms-2',
    orderInMilestone: 4,
    completionPercentage: 80,
    weekNumber: 37,
    year: 2026,
    lastSubmittedAt: '2026-09-11T12:00:00.000Z',
    isSubmittedLate: false,
  },

  // FE Tasks
  {
    id: 'tsk-1273',
    title: 'FE | Component CollapseMenu (Research + Implement)',
    role: 'FE',
    estimatedEffort: 2,
    actualEffort: 0,
    status: 'To do',
    assigneeAccount: 'TinhDD',
    milestoneId: 'ms-3',
    orderInMilestone: 1,
    completionPercentage: 0,
    weekNumber: 37,
    year: 2026,
  },
  {
    id: 'tsk-1275',
    title: 'Review code FE',
    role: 'FE',
    estimatedEffort: 16,
    actualEffort: 10,
    status: 'To do',
    assigneeAccount: 'DatTQ',
    milestoneId: 'ms-3',
    orderInMilestone: 2,
    completionPercentage: 30,
    weekNumber: 37,
    year: 2026,
    lastSubmittedAt: '2026-09-11T14:00:00.000Z',
    isSubmittedLate: false,
  },
  {
    id: 'tsk-1276',
    title: 'Convert CVA control to signal form control',
    role: 'FE',
    estimatedEffort: 16,
    actualEffort: 0,
    status: 'To do',
    assigneeAccount: 'DatTQ',
    milestoneId: 'ms-3',
    orderInMilestone: 3,
    completionPercentage: 0,
    weekNumber: 37,
    year: 2026,
  },
  {
    id: 'tsk-1277',
    title: 'Research FE Solution',
    role: 'FE',
    estimatedEffort: 8,
    actualEffort: 0,
    status: 'To do',
    assigneeAccount: 'DatTQ',
    milestoneId: 'ms-3',
    orderInMilestone: 4,
    completionPercentage: 0,
    weekNumber: 37,
    year: 2026,
  },
];
